<Project Sdk="Microsoft.NET.Sdk.Web">


  <ItemGroup>
    <PackageReference Include="ISOCodex.Countries" Version="1.0.0-alpha.1" />
  </ItemGroup>

<ItemGroup>
    <ProjectReference Include="..\..\src\Addressing\Addressing.csproj" />
    <ProjectReference Include="..\..\src\Addressing.Canada\Addressing.Canada.csproj" />
    <ProjectReference Include="..\..\src\Addressing.Spain\Addressing.Spain.csproj" />
    <ProjectReference Include="..\..\src\Addressing.France\Addressing.France.csproj" />
    <ProjectReference Include="..\..\src\Addressing.GreatBritain\Addressing.GreatBritain.csproj" />
    <ProjectReference Include="..\..\src\Addressing.Ireland\Addressing.Ireland.csproj" />
    <ProjectReference Include="..\..\src\Addressing.UnitedStates\Addressing.UnitedStates.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
