<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AssemblyName>ISOCodex.Addressing</AssemblyName>
    <RootNamespace>ISOCodex.Addressing</RootNamespace>

    <PackageId>ISOCodex.Addressing</PackageId>
    <Description>Domain model, formatting, and validation for international postal addresses.</Description>
    <PackageTags>address countrycode iso3166 domain-driven-design value-object</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ISOCodex.Countries" Version="1.0.0-alpha.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>true</Pack>
      <PackagePath></PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
